spring:
  datasource:
    # docker
#    url: jdbc:mysql://localhost:3307/bookdb
#    username: user
#    password: password

    # local
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: root123!@#

  jpa:
    hibernate:
      ddl-auto: create #validate
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true
#        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

logging.level.org:
  hibernate:
    SQL: debug
    orm.jdbc.bind: trace
#    type: trace
  springframework.security: TRACE