spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME:test_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123!@#}

  jpa:
    hibernate:
      ddl-auto: validate #validate
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true

  thymeleaf:
    cache: false

  messages:
    basename: errors

logging.level.org:
  hibernate:
    SQL: debug
    orm.jdbc.bind: trace
#    type: trace
  springframework.security: TRACE