spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME:test_db}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123!@#}

  jpa:
    hibernate:
      ddl-auto: update #validate
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true

  thymeleaf:
    cache: false

  messages:
    basename: errors

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging.level.org:
  hibernate:
    SQL: debug
    orm.jdbc.bind: trace
#    type: trace
  springframework.security: TRACE

app:
  upload:
    dir: C:/Users/User/Desktop/data/images/
  access:
    url: /images/

search:
  api:
    url: https://openapi.naver.com/v1/search/book_adv.json
    id: ${SEARCH_CLIENT_ID}
    secret: ${SEARCH_CLIENT_SECRET}